name: Tag

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        #      - name: Set up Go
        #        uses: actions/setup-go@v2
        #        with:
        #          go-version: 1.17

        # TODO: Do test / build here.

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: none
          DRY_RUN: true

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump_version.outputs.new_tag }}
          message: 'Creating tag: ${{ steps.bump_version.outputs.new_tag }}'
